version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  default: standard
  settings:
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
      allow-no-explanation: ["paralleltest", "tparallel"]
    wrapcheck:
      ignore-package-globs:
        - go.tkw01536.de/pkglib/errorsx
        - go.tkw01536.de/pkglib/exit
  enable:
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - govet
    - iface
    - intrange
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - tagalign
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck