name: CI

on: [push, pull_request]

env:
  GO_VERSION: '1.18.0-beta2' # '^1.18'
  GO_STABLE: 'false' # 'true'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - name: Run 'make lint'
        run: make lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - name: Run 'make testdeps'
        run: make testdeps
      - name: Run 'make test'
        run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - name: Install gogenlicense
        run: go install github.com/tkw1536/gogenlicense/cmd/gogenlicense@latest
      - uses: actions/checkout@v2
      - name: Run 'make generate'
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate
      - name: Run 'make all'
        run: make all
      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: dist/*
