name: CI

on: [push, pull_request]

env:
  GO_VERSION: '~1.25'
  GO_STABLE: 'true'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - name: Install cspell
        run: npm install -g cspell
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      - name: Run 'make spellcheck'
        run: make spellcheck
      - name: Run 'make lint'
        run: make lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - name: Run 'make testdeps'
        run: make testdeps
      - name: Run 'make test'
        run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Run 'make generate'
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate
      - name: Run 'make all'
        run: make all
      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/ggman
            dist/ggman_mac
            dist/ggman.exe
